### ISSUE TITLE
Call to /user/merge which doesn't exist in rakam api

### ISSUE THREAD

**Issue by fab-girard** [buremba/rakam-javascript#2]
Hello,
We are using the latest docker image of rakam API and lib from rakam.io CDN. As described in README, we use `rakam.setSuperProperties` to add some attributes to all events logged in rakam. But this call seems to call in addition `/user/merge` endpoint which doesn't exist in our API. This error doesn't seem to be problematic (data are correctly added/sent to all batch events). But I think it could be better to fix this error.

Fabien

**Comment by buremba** [comment]
Thanks for the report, @fab-girard. That endpoint actually exists in the enterprise version but the Javascript SDK doesn't seem to recognize that. I will update the SDK accordingly when I have time.

If you set the `userId` before logging any event, you should not see such an HTTP call.

**Comment by fab-girard** [comment]
Thank you for your answer and advice! It was my first feeling for enterprise version.
I've tried :
```
rakam.setUserId(userId); // waiting fix in rakam-js https://github.com/buremba/rakam-javascript/issues/2
rakam.logEvent(...
```
but it's not working (the ajax request is still performed)

**Comment by buremba** [comment]
Hey @fab-girard, the beta version that doesn't have `/user/merge` call in the community edition is released. You can use the URL `https://cdn.rakam.io/sdk/rakam.beta.min.js`.

**Comment by fab-girard** [comment]
sorry for this veeeeeeerrrrrrrrryyyyyyyy long delay for my answer! This seems to work fine, any chance to remove beta? maybe already deployed on main lib name?
